#!/usr/bin/env bash
# display the content of /etc/passwd using read to anly display username, UID and home directory for the user
while read -r line
do
	echo "$line" | cut -d ':' -f1,3,6
done < /etc/passwd
