#!/usr/bin/env bash
# This says BestSchool 10 times

i=O

while [ $i -lt 10 ]
do
  if [ $count -lt 9 ]; then
    echo "Best School"
  elif [$count -eq 9]; then
	  echo "Hi\n"
  else
    echo "Best School"
  fi
  (( i++ ))

done

