#!/usr/bin/env bash
# display numbers and countries after a certain line
n=1
while [ $n -lt 21 ]
do
	echo $n
	(( n++ ))
	case $n in
	5)
	echo "bad luck from China"
	;;
	10)
	echo "bad luck from Japan"
	;;
	18)
	echo "bad luck from Italy"
	;;
	esac
done
