#!/usr/bin/env bash
# displays hour from 0 to 12 with 59 minutes each one
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	(( hour++ ))
	case $hour in
	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13)
	echo {1..59} | tr ' ' '\n'
	;;
	esac
done
