#!/usr/bin/env bash
# Creates a file, displays response after receive sign 

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

while true
do
echo "To infinity and beyond"
sleep 2

trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM

done
